- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: yes

- name: Add user to group root
  user:
    name: "{{ user }}"
    groups: root
    state: present

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Add nginx configuration
  template:
    src: ../templates/site-conf.j2
    dest: /etc/nginx/sites-available/{{ website_name }}
    owner: "{{ user }}"
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Enable website configuration
  file:
    src: /etc/nginx/sites-available/{{ website_name }}
    dest: /etc/nginx/sites-enabled/{{ website_name }}
    state: link
  notify: Restart nginx

- name: Ensure nginx is running
  systemd:
    name: nginx
    state: started
